### ISSUE TITLE
Honors Theses 

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#10]
Delete "Degree Level" and "Degree Grantors." "Change Commencement Year" to "Date Awarded"

**Comment by mbstacy** [comment]
@ryancaillet @andrewjohnson314 Do you want fields to be optional or delete? Degree Grantors: defaults University of Colorado Boulder; Degree Level Not needed? Graduation not required for Honors Thesis?

**Comment by andrewjohnson314** [comment]
Correct. Students often defend/submit theses the semester before they graduate, and it's not a formal degree, so would be best to delete both. Thanks!

**Comment by mbstacy** [comment]
Complete
