### ISSUE TITLE
Remove Honors Program from Academic Affiliation LIst

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#17]

**Comment by mbstacy** [comment]
Complete: `Honors Program` Removed

**Comment by mbstacy** [comment]
Problems with Academic Affiliation

**Comment by mbstacy** [comment]
I had to keep Honors Program. Some did not have an academic affiliation. We can get rid of this in the future.

**Comment by andrewjohnson314** [comment]
We just discovered that some honors theses are "General Honors" (i.e., don't have a departmental affiliation), so we're going to need to keep Honors Program on the controlled list going forward anyway

**Comment by mbstacy** [comment]
Closing with  Honors Program remaining within controlled vocab.
