### ISSUE TITLE
Undergraduate theses

### ISSUE THREAD

**Issue by andrewjohnson314** [culibraries/ir-scholar#19]
https://scholar.colorado.edu/honr_theses/
https://scholar.colorado.edu/advert_ugrad/
https://scholar.colorado.edu/comm_ugrad/
https://scholar.colorado.edu/journ_ugrad/
https://scholar.colorado.edu/media_ugrad/

**Comment by mbstacy** [comment]
URLs for Undergrad Thesis. 
Query API: document_type: Thesis , front_end_url start with 5 urls above
Issue Completed:

1. script parse metadata identifying Undergrad theses

**Comment by mbstacy** [comment]
Complete
