### ISSUE TITLE
Strange document types

### ISSUE THREAD

**Issue by andrewjohnson314** [culibraries/ir-scholar#20]
Ignore everything with these URLs:

https://scholar.colorado.edu/learnerslunch/...
https://scholar.colorado.edu/oaweek/...

Map the following document_types to "Other Works":

bookreview
book_review
editorial
leg_brief
leg_pub
memo
nepc_review
pol_brief
re_brief
(Blanks)

**Comment by mbstacy** [comment]
@andrewjohnson314 can you map resource_type to above doc_types? Please take a look at [ Issue 16 ](https://github.com/culibraries/ir-scholar/issues/16 ) for resource types.

**Comment by andrewjohnson314** [comment]
We can use resource_type "Other" for all of these.

**Comment by mbstacy** [comment]
Loaded with "Other Works"
