### ISSUE TITLE
Make Academic Affiliation repeatable for Graduate Thesis or Dissertation

### ISSUE THREAD

**Issue by andrewjohnson314** [culibraries/ir-scholar#22]
Katie discovered some legitimate multiple affiliations for a handful of ETDs, so could we please make Academic Affiliation repeatable for the Graduate Thesis or Dissertation work type going forward? We don't need to do anything with the content that has already been migrated.

**Comment by mbstacy** [comment]
@andrewjohnson314 What about Undergrad? Should this be multiple as well?

**Comment by andrewjohnson314** [comment]
Yeah, let's do that. Probably better safe than sorry. Could be a double major or something down the road that we've never seen before. Thanks!

**Comment by andrewjohnson314** [comment]
Sorry I led you astray on this one initially!

**Comment by mbstacy** [comment]
Done. Will implement on next release.
