### ISSUE TITLE
Error Request Entity Too Large

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#25]
Got the above error with a PDF 77.45 MB.

**Comment by mbstacy** [comment]
Yes, current limit is 50 MB. What should the max file size upload limit? 1G? 2G?
@ryancaillet  @andrewjohnson314

**Comment by andrewjohnson314** [comment]
Let's go with 2GB per file max.

**Comment by mbstacy** [comment]
@andrewjohnson314 @ryancaillet Per request from Melissa Cantrell the file max size will expand to 10GB.
