### ISSUE TITLE
Embargo not ending

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#28]
This honors thesis shows up as embargoed even though it should have ended 12/21/19

https://scholar.colorado.edu/concern/graduate_thesis_or_dissertations/fb4948489

**Comment by mbstacy** [comment]
@ryancaillet Please read this documentation: https://samvera.github.io/lease-embargoes-2.0.html#embargoes I think hyrax requires active user participation in releasing embargoes. They do give you a tab to organize all embargoes to release. There may be a setting that I can change this but for now think it requires release action.

**Comment by mbstacy** [comment]
I will keep open for a while to see if I run across a flag to allow automatic embargo release.

**Comment by ryancaillet** [comment]
Great, thanks!

**Comment by mbstacy** [comment]
Done
