### ISSUE TITLE
test-scholar URL still showing up.

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#29]

**Comment by mbstacy** [comment]
@ryancaillet this will be the case. The test instance will be online this week. This will have no connection to the production site. Currently it was setup that way, but changed this morning to just showing empty URL. The test instance is where I will do all my trouble shooting and not touch production until solution is found!

**Comment by mbstacy** [comment]
@ryancaillet Just found what you are talking about. Need to change the host. Found the code in application_controller.rb . This will be a hot fix and pushed quickly.

**Comment by mbstacy** [comment]
https://github.com/culibraries/ir-scholar/blob/master/app/controllers/application_controller.rb#L4
