### ISSUE TITLE
Users can't add to collection.

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#30]
Wasn't sure if this was by design or not.

**Comment by mbstacy** [comment]
@ryancaillet This should not be the case. Under Dashboard >> Settings >> Collections >> Collection Types . If you edit User Collections you will see 'Participants' tab. All registered users can create a User Collection. I need more information. I will have Fred create a collection and get back with you. Fred is not an Admin.

**Comment by ryancaillet** [comment]
@mbstacy Thanks for looking into this. People from CIRES add the MeCCO data and summaries but couldn't weren't able to find the collections in the relationships tab.

**Comment by mbstacy** [comment]
@ryancaillet  Sorry, misunderstood the problem. They are able to create but unable to see collection to add a work to collection?

**Comment by ryancaillet** [comment]
@mbstacy I created the MeCCO collections back in December. I'm not sure if the user can create collections, but she couldn't find the MeCCO ones I made to add content to them.

**Comment by ryancaillet** [comment]
@mbstacy I think I solved my problem. I didn't see the "add user" feature under collection settings.

**Comment by mbstacy** [comment]
@dutr5288 has updated permissions.
