### ISSUE TITLE
Dataset Submission Errors

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#4]
I tried submitting a small zip file twice. I got a "RuntimeError in Hyrax::DatasetsController#create" error the first time and a 502 error the second time. 

![data_error](https://user-images.githubusercontent.com/56968017/67493434-18b93000-f635-11e9-9af9-2e1d20ce34f2.jpg)

**Comment by ryancaillet** [comment]
Worked the third time after logging out and logging back in.

**Comment by mbstacy** [comment]
Interesting! I have not run across this error. I will double-check using zip file.

**Comment by mbstacy** [comment]
I think this was an error that occurred because of a restart of the server or part of the system architecture that was being restarted. Will leave open.

**Comment by mbstacy** [comment]
Was not able to recreate. I believe the metadata issues have been resolved!
