### ISSUE TITLE
Make Abstract Required on all Work Types

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#5]

**Comment by mbstacy** [comment]
I agree but thought @andrewjohnson314  did not want this to be a requirement.

**Comment by mbstacy** [comment]
No, this can be changed.

**Comment by mbstacy** [comment]
I had to make Abstract optional! 1440 items without Abstract.

**Comment by mbstacy** [comment]
Closing Issue! We can reopen if later resolution is found for the 1440 items without abstracts.
