### ISSUE TITLE
OAI-PMH integration with Blacklight

### ISSUE THREAD

**Issue by mbstacy** [culibraries/ir-scholar#62]
Samvera Hyrax uses Blacklight as the discovery system. Blacklight provides an OAI-PMH component.

Required for `One Search` Integration

**Comment by andrewjohnson314** [comment]
Change download links from Source to Identifier field per Unpaywall recommendations: https://support.unpaywall.org/support/solutions/articles/44001937113-how-are-documents-located-from-repository-records-

**Comment by andrewjohnson314** [comment]
Also, would be good to add another Identifier field with DOI (if applicable): https://support.unpaywall.org/support/solutions/articles/44001937102-how-are-repository-records-matched-to-published-articles-

And two Rights fields for our Rights Statement and License fields from CU Scholar: https://support.unpaywall.org/support/solutions/articles/44002198169-recommendation-for-irs-license-reporting

**Comment by andrewjohnson314** [comment]
Changes needed:

- Use Identifier (instead of Source) for download links
- Delete Source field
- Add third Identifier field for DOIs (when applicable)
- Add two Rights fields (one for Rights Statement and one for License)
- Waiting on what to do about Academic Affiliation (AJ will edit this once we have a decision)

**Comment by mbstacy** [comment]
@andrewjohnson314 @ryancaillet I have pushed the OAI-PMH to the test server. 

Please review: https://test-scholar.colorado.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc

All public items within CU Scholar are published to OAI-PMH

Academic Affiliation: 
1. oai_publish ==> false  --> Not added to subject field 
2. oai_publish ==> Not present --> Publish to subject field
3.  If item not in Academic Affiliation lookup file --> Publish to subject field(???)

The other fixed item was the degree_grantor field set to the Publisher field(Only for ETDs and Undergrad Honors Thesis).

**Comment by andrewjohnson314** [comment]
@mbstacy looks good! I would say for 3 to not publish to subject field in that case. Otherwise, I think we're all set.
