### ISSUE TITLE
Date Issued field

### ISSUE THREAD

**Issue by ryancaillet** [culibraries/ir-scholar#8]
Use MM-DD-YYYY format, but should allow just YYYY or MM-YYYY if submitter don't have an exact date for a work.

**Comment by andrewjohnson314** [comment]
Just to clarify, we do want YYYY-MM-DD as the general format, but we want to allow for YYYY-MM or YYYY as well. We will definitely have content that only has YYYY.

**Comment by mbstacy** [comment]
Final allowed formats: YYYY_MM_DD, YYYY-MM, YYYY 
@dutr5288 will need to update validation rule.

**Comment by mbstacy** [comment]
@dutr5288 validation rule must also allow nil values

**Comment by andrewjohnson314** [comment]
If it's easier, why don't we just make this required? I think everything has/needs this field. We don't have to worry about that before the data ingest, but let's go with that whenever we turn the validation back on.

**Comment by mbstacy** [comment]
@andrewjohnson314 Date Issued required for all work types? correct?

**Comment by andrewjohnson314** [comment]
Correct!

**Comment by mbstacy** [comment]
Complete
